# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. By starting with 1 and 2, the first 10 terms will
# be: # 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.
# (Link: https://projecteuler.net/problem=2.)

def sum_even_fibonacci_terms(limit):
    """Returns the sum of even fibonacci numbers below a given limit.
    """
    # Initializing the Fibonacci sequence:
    second_to_last_term = 1
    last_term = 1
    sum = 0
    # Appending numbers below the limit:
    while last_term < limit:
        new_term = last_term + second_to_last_term
        second_to_last_term = last_term
        last_term = new_term
        # Summing even numbers:
        if new_term % 2 == 0:
            sum += new_term
    return sum

print(sum_even_fibonacci_terms(4000000))